// Generated by CoffeeScript 1.6.3
(function() {
  var first;

  first = {
    init: function() {
      this.initBindings();
      return this.everyoneGetsBoxes(100);
    },
    initBindings: function() {
      return $(document).on("click", ".box", function(e) {
        var $currentTarget;
        $currentTarget = $(e.currentTarget);
        return $currentTarget.addClass("gocrazy");
      });
    },
    everyoneGetsBoxes: function(num) {
      return _(num).times(function(i) {
        var $newBox;
        $newBox = $("<div></div>").addClass("box").attr("id", "box" + i);
        return $("body").append($newBox);
      });
    }
  };

  first.init();

  _.each($(".box"), function(box, i) {
    var newColor;
    console.log(box);
    newColor = "rgba(" + (i * 3232) % 255 + "," + (i * 12319) % 255 + "," + (i * 242340) % 255 + ",50)";
    $(box).css("background-color", newColor);
    $(box).css("-webkit-transition", i * 0.1 + "s all linear");
    $(box).css("-webkit-transform-origin", (i * 23930) % 500 + "%" + (i * 392023) % 500 + "%");
    return $(box).addClass("gocrazy");
  });

}).call(this);
