// Generated by CoffeeScript 1.6.3
(function() {
  var first, rand, randWithNegs;

  rand = function(top) {
    return Math.floor((Math.random() * top) + 1);
  };

  randWithNegs = function(maxMin) {
    return Math.floor((Math.random() * top) - 1);
  };

  first = {
    init: function() {
      this.everyoneGetsBoxes(100);
      this.initBindings();
      return this.run();
    },
    initBindings: function() {
      $(".launch-box").click(function(e) {
        return first.run();
      });
      $("body").click(function() {
        return first.run;
      });
      return $(document).on("click", ".box", function(e) {
        var $currentTarget;
        $currentTarget = $(e.currentTarget);
        return $currentTarget.addClass("gocrazy");
      });
    },
    everyoneGetsBoxes: function(num) {
      return _(num).times(function() {
        var $newBox, boxCount, boxId, newColor;
        boxCount = $(".box").length;
        boxId = boxCount + 1;
        newColor = "rgba(" + rand(255) + "," + rand(255) + "," + rand(255) + ",50)";
        $newBox = $("<div></div>").addClass("box").attr("id", "box" + boxId);
        $(".main.wrapper").prepend($newBox);
        return boxId;
      });
    },
    transformBox: function($box) {
      var newColor;
      newColor = "rgba(" + rand(255) + "," + rand(255) + "," + rand(255) + ",50)";
      $box.css("-webkit-transition", "1s all linear");
      $box.css("background-color", newColor);
      $box.css("-webkit-transform-origin", rand(500) + "%" + rand(500) + "%");
      return $box.css("-webkit-transform", "rotate(" + rand(360) + "deg)");
    },
    run: function() {
      var boxId;
      boxId = first.everyoneGetsBoxes(1);
      return first.transformBox($("#box" + boxId));
    }
  };

  first.initBindings();

}).call(this);
