// Generated by CoffeeScript 1.6.3
(function() {
  var lineScratch;

  $(document).ready(function() {
    lineScratch.draw();
    $(".path-data-input").val(lineScratch.pathDataString);
    return $(".path-data-input").keypress(function() {
      var newPathData;
      newPathData = $(".path-data-input").val();
      console.log(newPathData);
      lineScratch.pathDataString = newPathData;
      return lineScratch.draw();
    });
  });

  lineScratch = {
    pathDataString: "M100,200 C100,100 250,100 250,200 S400,300 400,200",
    draw: function() {
      var scratchPath;
      scratchPath = this.buildPath(this.pathDataString, "scratch-path");
      $("svg").empty();
      return $("svg").append(scratchPath);
    },
    buildPath: function(pathDataString, pathClass) {
      var path;
      path = document.createElementNS("http://www.w3.org/2000/svg", "path");
      path.setAttribute("d", pathDataString);
      path.setAttribute("class", pathClass);
      return path;
    }
  };

}).call(this);
