// Generated by CoffeeScript 1.6.3
(function() {
  window.reader = {
    text: [],
    position: 0,
    init: function() {
      reader.renderReadTape();
      reader.setupPageText();
      reader.updateTape(reader.position);
      return reader.initBindings();
    },
    initBindings: function() {
      KeyboardJS.on('left', reader.moveLeft);
      return KeyboardJS.on('right', reader.moveRight);
    },
    setupPageText: function() {
      var raw_text;
      raw_text = $('body').children(":visible").text();
      return reader.text = reader.cleanupText(raw_text);
    },
    moveLeft: function() {
      if (reader.position > 0) {
        reader.position -= 1;
        return reader.updateTape(reader.position);
      }
    },
    moveRight: function() {
      if (reader.position < reader.text.length) {
        reader.position += 1;
        return reader.updateTape(reader.position);
      }
    },
    updateTape: function(position) {
      var focusText, leftText, rightText;
      leftText = "";
      if (position === 0) {
        leftText = "";
      } else {
        leftText = reader.text.slice(0, position).join(" ");
      }
      rightText = reader.text.slice(position + 1, reader.text.length).join(" ");
      focusText = reader.text[position];
      reader.populateLeftTape(leftText);
      reader.populateRightTape(rightText);
      return reader.populateFocus(focusText);
    },
    cleanupText: function(text) {
      text = text.replace("↵", "");
      return text = text.split(' ');
    },
    renderReadTape: function() {
      return $('body').prepend("<span class='tape left'></span><span class='focus'></span><span class='tape right'></span>");
    },
    populateLeftTape: function(str) {
      return $('.tape.left').text(str);
    },
    populateRightTape: function(str) {
      return $('.tape.right').text(str);
    },
    populateFocus: function(str) {
      return $('.focus').text(str);
    }
  };

}).call(this);
